export const BANES = [
  { name: "Blinded", url: "https://openlegendrpg.com/bane/blinded", icon: "../icons/banes/blinded.png" },
  { name: "Charmed", url: "https://openlegendrpg.com/bane/charmed", icon: "../icons/banes/charmed.png" },
  { name: "Deafened", url: "https://openlegendrpg.com/bane/deafened", icon: "../icons/banes/deafend.png" },
  { name: "Death", url: "https://openlegendrpg.com/bane/death", icon: "../icons/banes/death.png" },
  { name: "Demoralized", url: "https://openlegendrpg.com/bane/demoralized", icon: "../icons/banes/demoralized.png" },
  { name: "Disarmed", url: "https://openlegendrpg.com/bane/disarmed", icon: "../icons/banes/disarmed.png" },
  { name: "Dominated", url: "https://openlegendrpg.com/bane/dominated", icon: "../icons/banes/dominated.png" },
  { name: "Fatigued", url: "https://openlegendrpg.com/bane/fatigued", icon: "../icons/banes/fatigued.png" },
  { name: "Fear", url: "https://openlegendrpg.com/bane/fear", icon: "../icons/banes/fear.png" },
  { name: "Forced Move", url: "https://openlegendrpg.com/bane/forced-move", icon: "../icons/banes/forced.png" },
  { name: "Immobile", url: "https://openlegendrpg.com/bane/immobile", icon: "../icons/banes/immobile.png" },
  { name: "Incapacitated", url: "https://openlegendrpg.com/bane/incapacitated", icon: "../icons/banes/incapacitated.png" },
  { name: "Knockdown", url: "https://openlegendrpg.com/bane/knockdown", icon: "../icons/banes/knockdown.png" },
  { name: "Memory Alteration", url: "https://openlegendrpg.com/bane/memory-alteration", icon: "../icons/banes/memory.png" },
  { name: "Mind Dredge", url: "https://openlegendrpg.com/bane/mind-dredge", icon: "../icons/banes/mind.png" },
  { name: "Nullify", url: "https://openlegendrpg.com/bane/nullify", icon: "../icons/banes/nulify.png" },
  { name: "Persistent Damage", url: "https://openlegendrpg.com/bane/persistent-damage", icon: "../icons/banes/persistent.png" },
  { name: "Phantasm", url: "https://openlegendrpg.com/bane/phantasm", icon: "../icons/banes/phantasm.png" },
  { name: "Polymorph", url: "https://openlegendrpg.com/bane/polymorph", icon: "../icons/banes/polymorph.png" },
  { name: "Provoked", url: "https://openlegendrpg.com/bane/provoked", icon: "../icons/banes/provoked.png" },
  { name: "Spying", url: "https://openlegendrpg.com/bane/spying", icon: "../icons/banes/spying.png" },
  { name: "Sickened", url: "https://openlegendrpg.com/bane/sickened", icon: "../icons/banes/sickend.png" },
  { name: "Silenced", url: "https://openlegendrpg.com/bane/silenced", icon: "../icons/banes/silenced.png" },
  { name: "Slowed", url: "https://openlegendrpg.com/bane/slowed", icon: "../icons/banes/slowed.png" },
  { name: "Stunned", url: "https://openlegendrpg.com/bane/stunned", icon: "../icons/banes/stunned.png" },
  { name: "Stupefied", url: "https://openlegendrpg.com/bane/stupefied", icon: "../icons/banes/stupified.png" },
  { name: "Truthfulness", url: "https://openlegendrpg.com/bane/truthfulness", icon: "../icons/banes/truyhfulness.png" }
];
