export const OPENLEGEND_BANES = [
  {
    "id": "blinded",
    "name": "Blinded",
    "displayTitle": "Blinded",
    "slug": "blinded",
    "url": "https://openlegendrpg.com/bane/blinded",
    "icon": "../icons/banes/blinded.png",
    "summary": "Reference entry for the Blinded bane.",
    "description": "Local builder entry for Blinded. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Blinded. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "charmed",
    "name": "Charmed",
    "displayTitle": "Charmed",
    "slug": "charmed",
    "url": "https://openlegendrpg.com/bane/charmed",
    "icon": "../icons/banes/charmed.png",
    "summary": "Reference entry for the Charmed bane.",
    "description": "Local builder entry for Charmed. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Charmed. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "deafened",
    "name": "Deafened",
    "displayTitle": "Deafened",
    "slug": "deafened",
    "url": "https://openlegendrpg.com/bane/deafened",
    "icon": "../icons/banes/deafend.png",
    "summary": "Reference entry for the Deafened bane.",
    "description": "Local builder entry for Deafened. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Deafened. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "death",
    "name": "Death",
    "displayTitle": "Death",
    "slug": "death",
    "url": "https://openlegendrpg.com/bane/death",
    "icon": "../icons/banes/death.png",
    "summary": "Reference entry for the Death bane.",
    "description": "Local builder entry for Death. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Death. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "demoralized",
    "name": "Demoralized",
    "displayTitle": "Demoralized",
    "slug": "demoralized",
    "url": "https://openlegendrpg.com/bane/demoralized",
    "icon": "../icons/banes/demoralized.png",
    "summary": "Reference entry for the Demoralized bane.",
    "description": "Local builder entry for Demoralized. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Demoralized. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "disarmed",
    "name": "Disarmed",
    "displayTitle": "Disarmed",
    "slug": "disarmed",
    "url": "https://openlegendrpg.com/bane/disarmed",
    "icon": "../icons/banes/disarmed.png",
    "summary": "Reference entry for the Disarmed bane.",
    "description": "Local builder entry for Disarmed. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Disarmed. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "dominated",
    "name": "Dominated",
    "displayTitle": "Dominated",
    "slug": "dominated",
    "url": "https://openlegendrpg.com/bane/dominated",
    "icon": "../icons/banes/dominated.png",
    "summary": "Reference entry for the Dominated bane.",
    "description": "Local builder entry for Dominated. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Dominated. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "fatigued",
    "name": "Fatigued",
    "displayTitle": "Fatigued",
    "slug": "fatigued",
    "url": "https://openlegendrpg.com/bane/fatigued",
    "icon": "../icons/banes/fatigued.png",
    "summary": "Reference entry for the Fatigued bane.",
    "description": "Local builder entry for Fatigued. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Fatigued. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "fear",
    "name": "Fear",
    "displayTitle": "Fear",
    "slug": "fear",
    "url": "https://openlegendrpg.com/bane/fear",
    "icon": "../icons/banes/fear.png",
    "summary": "Reference entry for the Fear bane.",
    "description": "Local builder entry for Fear. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Fear. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "forcedmove",
    "name": "Forced Move",
    "displayTitle": "Forced Move",
    "slug": "forced-move",
    "url": "https://openlegendrpg.com/bane/forced-move",
    "icon": "../icons/banes/forced.png",
    "summary": "Reference entry for the Forced Move bane.",
    "description": "Local builder entry for Forced Move. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Forced Move. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "immobile",
    "name": "Immobile",
    "displayTitle": "Immobile",
    "slug": "immobile",
    "url": "https://openlegendrpg.com/bane/immobile",
    "icon": "../icons/banes/immobile.png",
    "summary": "Reference entry for the Immobile bane.",
    "description": "Local builder entry for Immobile. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Immobile. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "incapacitated",
    "name": "Incapacitated",
    "displayTitle": "Incapacitated",
    "slug": "incapacitated",
    "url": "https://openlegendrpg.com/bane/incapacitated",
    "icon": "../icons/banes/incapacitated.png",
    "summary": "Reference entry for the Incapacitated bane.",
    "description": "Local builder entry for Incapacitated. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Incapacitated. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "knockdown",
    "name": "Knockdown",
    "displayTitle": "Knockdown",
    "slug": "knockdown",
    "url": "https://openlegendrpg.com/bane/knockdown",
    "icon": "../icons/banes/knockdown.png",
    "summary": "Reference entry for the Knockdown bane.",
    "description": "Local builder entry for Knockdown. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Knockdown. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "memoryalteration",
    "name": "Memory Alteration",
    "displayTitle": "Memory Alteration",
    "slug": "memory-alteration",
    "url": "https://openlegendrpg.com/bane/memory-alteration",
    "icon": "../icons/banes/memory.png",
    "summary": "Reference entry for the Memory Alteration bane.",
    "description": "Local builder entry for Memory Alteration. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Memory Alteration. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "minddredge",
    "name": "Mind Dredge",
    "displayTitle": "Mind Dredge",
    "slug": "mind-dredge",
    "url": "https://openlegendrpg.com/bane/mind-dredge",
    "icon": "../icons/banes/mind.png",
    "summary": "Reference entry for the Mind Dredge bane.",
    "description": "Local builder entry for Mind Dredge. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Mind Dredge. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "nullify",
    "name": "Nullify",
    "displayTitle": "Nullify",
    "slug": "nullify",
    "url": "https://openlegendrpg.com/bane/nullify",
    "icon": "../icons/banes/nulify.png",
    "summary": "Reference entry for the Nullify bane.",
    "description": "Local builder entry for Nullify. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Nullify. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "persistentdamage",
    "name": "Persistent Damage",
    "displayTitle": "Persistent Damage",
    "slug": "persistent-damage",
    "url": "https://openlegendrpg.com/bane/persistent-damage",
    "icon": "../icons/banes/persistent.png",
    "summary": "Reference entry for the Persistent Damage bane.",
    "description": "Local builder entry for Persistent Damage. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Persistent Damage. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "phantasm",
    "name": "Phantasm",
    "displayTitle": "Phantasm",
    "slug": "phantasm",
    "url": "https://openlegendrpg.com/bane/phantasm",
    "icon": "../icons/banes/phantasm.png",
    "summary": "Reference entry for the Phantasm bane.",
    "description": "Local builder entry for Phantasm. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Phantasm. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "polymorph",
    "name": "Polymorph",
    "displayTitle": "Polymorph",
    "slug": "polymorph",
    "url": "https://openlegendrpg.com/bane/polymorph",
    "icon": "../icons/banes/polymorph.png",
    "summary": "Reference entry for the Polymorph bane.",
    "description": "Local builder entry for Polymorph. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Polymorph. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "provoked",
    "name": "Provoked",
    "displayTitle": "Provoked",
    "slug": "provoked",
    "url": "https://openlegendrpg.com/bane/provoked",
    "icon": "../icons/banes/provoked.png",
    "summary": "Reference entry for the Provoked bane.",
    "description": "Local builder entry for Provoked. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Provoked. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "spying",
    "name": "Spying",
    "displayTitle": "Spying",
    "slug": "spying",
    "url": "https://openlegendrpg.com/bane/spying",
    "icon": "../icons/banes/spying.png",
    "summary": "Reference entry for the Spying bane.",
    "description": "Local builder entry for Spying. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Spying. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "sickened",
    "name": "Sickened",
    "displayTitle": "Sickened",
    "slug": "sickened",
    "url": "https://openlegendrpg.com/bane/sickened",
    "icon": "../icons/banes/sickend.png",
    "summary": "Reference entry for the Sickened bane.",
    "description": "Local builder entry for Sickened. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Sickened. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "silenced",
    "name": "Silenced",
    "displayTitle": "Silenced",
    "slug": "silenced",
    "url": "https://openlegendrpg.com/bane/silenced",
    "icon": "../icons/banes/silenced.png",
    "summary": "Reference entry for the Silenced bane.",
    "description": "Local builder entry for Silenced. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Silenced. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "slowed",
    "name": "Slowed",
    "displayTitle": "Slowed",
    "slug": "slowed",
    "url": "https://openlegendrpg.com/bane/slowed",
    "icon": "../icons/banes/slowed.png",
    "summary": "Reference entry for the Slowed bane.",
    "description": "Local builder entry for Slowed. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Slowed. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "stunned",
    "name": "Stunned",
    "displayTitle": "Stunned",
    "slug": "stunned",
    "url": "https://openlegendrpg.com/bane/stunned",
    "icon": "../icons/banes/stunned.png",
    "summary": "Reference entry for the Stunned bane.",
    "description": "Local builder entry for Stunned. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Stunned. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "stupefied",
    "name": "Stupefied",
    "displayTitle": "Stupefied",
    "slug": "stupefied",
    "url": "https://openlegendrpg.com/bane/stupefied",
    "icon": "../icons/banes/stupified.png",
    "summary": "Reference entry for the Stupefied bane.",
    "description": "Local builder entry for Stupefied. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Stupefied. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  },
  {
    "id": "truthfulness",
    "name": "Truthfulness",
    "displayTitle": "Truthfulness",
    "slug": "truthfulness",
    "url": "https://openlegendrpg.com/bane/truthfulness",
    "icon": "../icons/banes/truyhfulness.png",
    "summary": "Reference entry for the Truthfulness bane.",
    "description": "Local builder entry for Truthfulness. Use the official bane page for the full Open Legend rules text and power level details.",
    "descriptionHtml": "Local builder entry for Truthfulness. Use the official bane page for the full Open Legend rules text and power level details.",
    "effectHtml": ""
  }
];
